### ISSUE TITLE
Styles inserted with JS contains multiple BR tags

### ISSUE THREAD

**Issue by tangar76** [swissup/range-slider#1]
![image](https://user-images.githubusercontent.com/13131588/210221995-b6d15bcd-5b96-4aeb-826b-e26c0e40aeaf.png)

Open `styles` element created by range-slider via browser DevTools. There are BR tag for every new line.

**Comment by tangar76** [comment]
Maybe it is better to use `innerHTML` instead of `innerText` at https://github.com/swissup/range-slider/blob/master/range-slider.js#L133

**Comment by vovayatsyuk** [comment]
I always wanted to move the styles to separate css, so it's not an issue anymore: https://github.com/swissup/range-slider/commit/881ece1a7577af3764a4ed4931611843e832455b

This allows to create range sliders with [zero layout shift](https://github.com/swissup/range-slider#prevent-cls)! 🎉
